common: &common
  adapter: postgresql
  username: school_fit
  password: password # from psql setup, see Postgresql

development:
  <<: *common
  database: school_fit_development

test:
  <<: *common
  database: school_fit_test

production:
  <<: *common
  database: school_fit_production
